FROM scratch AS builder
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-web-services/2.1.4.RELEASE/spring-boot-starter-web-services-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-data-rest/2.1.4.RELEASE/spring-boot-starter-data-rest-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-actuator/2.1.4.RELEASE/spring-boot-starter-actuator-2.1.4.RELEASE.jar /jars/
ADD https://repo.spring.io/plugins-release/io/springfox/springfox-swagger2/2.9.0/springfox-swagger2-2.9.0.jar /jars/
ADD https://repo.spring.io/plugins-release/io/springfox/springfox-swagger-ui/2.9.0/springfox-swagger-ui-2.9.0.jar /jars/
ADD http://central.maven.org/maven2/net/logstash/logback/logstash-logback-encoder/5.1/logstash-logback-encoder-5.1.jar /jars/
ADD http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-autoconfigure/2.1.4.RELEASE/spring-boot-autoconfigure-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-web/2.1.4.RELEASE/spring-boot-starter-web-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-web/2.1.4.RELEASE/spring-boot-starter-web-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-json/2.1.4.RELEASE/spring-boot-starter-json-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.8/jackson-datatype-jsr310-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/data/spring-data-rest-webmvc/3.1.6.RELEASE/spring-data-rest-webmvc-3.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/data/spring-data-rest-core/3.1.6.RELEASE/spring-data-rest-core-3.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.8/jackson-datatype-jdk8-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.8/jackson-module-parameter-names-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/jaxws-tools/2.3.2/jaxws-tools-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/sdo-eclipselink-plugin/2.3.2/sdo-eclipselink-plugin-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/jaxws-rt/2.3.2/jaxws-rt-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/messaging/saaj/saaj-impl/1.5.1/saaj-impl-1.5.1.jar /jars/
ADD http://central.maven.org/maven2/org/jvnet/mimepull/mimepull/1.9.11/mimepull-1.9.11.jar /jars/
ADD http://central.maven.org/maven2/jakarta/xml/soap/jakarta.xml.soap-api/1.4.1/jakarta.xml.soap-api-1.4.1.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.17/tomcat-embed-websocket-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-core/9.0.17/tomcat-embed-core-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-ws-addr/3.1.12/cxf-rt-ws-addr-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-bindings-soap/3.1.12/cxf-rt-bindings-soap-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-databinding-jaxb/3.1.12/cxf-rt-databinding-jaxb-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-web/2.1.4.RELEASE/spring-boot-starter-web-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-web/2.1.4.RELEASE/spring-boot-starter-web-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-json/2.1.4.RELEASE/spring-boot-starter-json-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.8/jackson-datatype-jsr310-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/data/spring-data-rest-webmvc/3.1.6.RELEASE/spring-data-rest-webmvc-3.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/data/spring-data-rest-core/3.1.6.RELEASE/spring-data-rest-core-3.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.8/jackson-datatype-jdk8-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.8/jackson-module-parameter-names-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/jaxws-tools/2.3.2/jaxws-tools-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/sdo-eclipselink-plugin/2.3.2/sdo-eclipselink-plugin-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/jaxws-rt/2.3.2/jaxws-rt-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/messaging/saaj/saaj-impl/1.5.1/saaj-impl-1.5.1.jar /jars/
ADD http://central.maven.org/maven2/org/jvnet/mimepull/mimepull/1.9.11/mimepull-1.9.11.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-frontend-jaxws/3.1.12/cxf-rt-frontend-jaxws-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/jakarta/xml/soap/jakarta.xml.soap-api/1.4.1/jakarta.xml.soap-api-1.4.1.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.17/tomcat-embed-websocket-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-core/9.0.17/tomcat-embed-core-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-ws-addr/3.1.12/cxf-rt-ws-addr-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-bindings-soap/3.1.12/cxf-rt-bindings-soap-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-databinding-jaxb/3.1.12/cxf-rt-databinding-jaxb-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.2/jaxb-impl-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/bind/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar /jars/
ADD http://central.maven.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar /jars/
ADD http://central.maven.org/maven2/org/codehaus/jettison/jettison/1.3.8/jettison-1.3.8.jar /jars/
ADD http://central.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar /jars/
ADD http://central.maven.org/maven2/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar /jars/
ADD http://central.maven.org/maven2/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar /jars/
ADD http://central.maven.org/maven2/javax/xml/ws/jaxws-api/2.3.1/jaxws-api-2.3.1.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter/2.1.4.RELEASE/spring-boot-starter-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/javax/xml/ws/jaxws-api/2.3.1/jaxws-api-2.3.1.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter/2.1.4.RELEASE/spring-boot-starter-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/io/swagger/swagger-models/1.5.18/swagger-models-1.5.18.jar /jars/
ADD http://central.maven.org/maven2/io/swagger/swagger-annotations/1.5.18/swagger-annotations-1.5.18.jar /jars/
ADD http://repo.spring.io/plugins-release/io/springfox/springfox-spi/2.9.0/springfox-spi-2.9.0.jar /jars/
ADD http://repo.spring.io/plugins-release/io/springfox/springfox-core/2.9.0/springfox-core-2.9.0.jar /jars/
ADD http://central.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar /jars/
ADD http://central.maven.org/maven2/org/hibernate/validator/hibernate-validator/6.0.16.Final/hibernate-validator-6.0.16.Final.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/classmate/1.4.0/classmate-1.4.0.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/plugin/spring-plugin-core/1.2.0.RELEASE/spring-plugin-core-1.2.0.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/plugin/spring-plugin-metadata/1.2.0.RELEASE/spring-plugin-metadata-1.2.0.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-features-logging/3.1.12/cxf-rt-features-logging-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/hateoas/spring-hateoas/0.25.0.RELEASE/spring-hateoas-0.25.0.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/data/spring-data-commons/2.1.6.RELEASE/spring-data-commons-2.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-logging/2.1.4.RELEASE/spring-boot-starter-logging-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar /jars/
ADD http://central.maven.org/maven2/org/apache/logging/log4j/log4j-to-slf4j/2.11.2/log4j-to-slf4j-2.11.2.jar /jars/
ADD http://central.maven.org/maven2/org/slf4j/jul-to-slf4j/1.7.26/jul-to-slf4j-1.7.26.jar /jars/
ADD http://central.maven.org/maven2/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar /jars/
ADD http://central.maven.org/maven2/org/mapstruct/mapstruct/1.2.0.Final/mapstruct-1.2.0.Final.jar /jars/
ADD http://central.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar /jars/
ADD http://central.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar /jars/
ADD http://central.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar /jars/
ADD http://central.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.9.3/jackson-annotations-2.9.3.jar /jars/
ADD http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/release-documentation/2.3.2/release-documentation-2.3.2-docbook.zip /jars/
ADD http://central.maven.org/maven2/jakarta/xml/ws/jakarta.xml.ws-api/2.3.2/jakarta.xml.ws-api-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.jar /jars/                                                                                                            
ADD http://central.maven.org/maven2/jakarta/xml/ws/jakarta.xml.ws-api/2.3.2/jakarta.xml.ws-api-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/jaxb/jaxb-runtime/2.3.2/jaxb-runtime-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/stream/buffer/streambuffer/1.5.7/streambuffer-1.5.7.jar /jars/
ADD http://central.maven.org/maven2/org/jvnet/staxex/stax-ex/1.8.1/stax-ex-1.8.1.jar /jars/
ADD http://central.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/jakarta/xml/soap/jakarta.xml.soap-api/1.4.1/jakarta.xml.soap-api-1.4.1.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/jaxws-eclipselink-plugin/2.3.2/jaxws-eclipselink-plugin-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-frontend-simple/3.1.12/cxf-rt-frontend-simple-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/jakarta/jws/jakarta.jws-api/1.1.1/jakarta.jws-api-1.1.1.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-webmvc/5.1.6.RELEASE/spring-webmvc-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-web/5.1.6.RELEASE/spring-web-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http/3.1.12/cxf-rt-transports-http-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-starter-tomcat/2.1.4.RELEASE/spring-boot-starter-tomcat-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/javax/xml/soap/javax.xml.soap-api/1.4.0/javax.xml.soap-api-1.4.0.jar /jars/
ADD http://central.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar /jars/
ADD http://central.maven.org/maven2/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/ws/spring-xml/3.0.7.RELEASE/spring-xml-3.0.7.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-autoconfigure/2.1.4.RELEASE/spring-boot-autoconfigure-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-actuator/2.1.4.RELEASE/spring-boot-actuator-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot/2.1.4.RELEASE/spring-boot-2.1.4.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-context/5.1.6.RELEASE/spring-context-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-aop/5.1.6.RELEASE/spring-aop-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-tx/5.1.6.RELEASE/spring-tx-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-beans/5.1.6.RELEASE/spring-beans-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-expression/5.1.6.RELEASE/spring-expression-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-core/5.1.6.RELEASE/spring-core-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/commons-io/commons-io/2.5/commons-io-2.5.jar /jars/
ADD http://central.maven.org/maven2/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar /jars/
ADD http://central.maven.org/maven2/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar /jars/
ADD http://central.maven.org/maven2/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar /jars/
ADD http://central.maven.org/maven2/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/ws/policy/2.7.6/policy-2.7.6.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/gmbal/gmbal/4.0.0/gmbal-4.0.0.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/fastinfoset/FastInfoset/1.2.16/FastInfoset-1.2.16.jar /jars/

FROM scratch
COPY --from=builder /jars/ /jars/
ADD http://central.maven.org/maven2/com/fasterxml/woodstox/woodstox-core/5.1.0/woodstox-core-5.1.0.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-bindings-xml/3.1.12/cxf-rt-bindings-xml-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-wsdl/3.1.12/cxf-rt-wsdl-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-rt-ws-policy/3.1.12/cxf-rt-ws-policy-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/apache/cxf/cxf-core/3.1.12/cxf-core-3.1.12.jar /jars/
ADD http://central.maven.org/maven2/org/codehaus/woodstox/woodstox-core-asl/4.4.1/woodstox-core-asl-4.4.1.jar /jars/
ADD http://central.maven.org/maven2/org/codehaus/woodstox/stax2-api/4.1/stax2-api-4.1.jar /jars/
ADD http://central.maven.org/maven2/com/sun/istack/istack-commons-runtime/3.0.8/istack-commons-runtime-3.0.8.jar /jars/
ADD http://central.maven.org/maven2/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/bind/jaxb-xjc/2.3.2/jaxb-xjc-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/com/sun/xml/bind/jaxb-jxc/2.3.2/jaxb-jxc-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/jakarta/mail/jakarta.mail-api/1.6.3/jakarta.mail-api-1.6.3.jar /jars/
ADD http://central.maven.org/maven2/jakarta/persistence/jakarta.persistence-api/2.2.2/jakarta.persistence-api-2.2.2.jar /jars/
ADD http://central.maven.org/maven2/org/eclipse/persistence/org.eclipse.persistence.sdo/2.7.4/org.eclipse.persistence.sdo-2.7.4.jar /jars/
ADD http://central.maven.org/maven2/org/eclipse/persistence/org.eclipse.persistence.moxy/2.7.4/org.eclipse.persistence.moxy-2.7.4.jar /jars/
ADD http://central.maven.org/maven2/org/eclipse/persistence/commonj.sdo/2.1.1/commonj.sdo-2.1.1.jar /jars/
ADD http://central.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar /jars/
ADD http://central.maven.org/maven2/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.17/tomcat-embed-websocket-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-core/9.0.17/tomcat-embed-core-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-el/9.0.17/tomcat-embed-el-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-core/9.0.17/tomcat-embed-core-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/embed/tomcat-embed-el/9.0.17/tomcat-embed-el-9.0.17.jar /jars/
ADD http://central.maven.org/maven2/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar /jars/
ADD http://central.maven.org/maven2/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar /jars/
ADD http://central.maven.org/maven2/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-jcl/5.1.6.RELEASE/spring-jcl-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/atteo/evo-inflector/1.2.2/evo-inflector-1.2.2.jar /jars/
ADD http://central.maven.org/maven2/net/bytebuddy/byte-buddy/1.8.8/byte-buddy-1.8.8.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/jaxb/txw2/2.3.2/txw2-2.3.2.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/external/management-api/3.2.1/management-api-3.2.1.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/pfl/pfl-tf-tools/4.0.1/pfl-tf-tools-4.0.1.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/pfl/pfl-basic-tools/4.0.1/pfl-basic-tools-4.0.1.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/pfl/pfl-tf/4.0.1/pfl-tf-4.0.1.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/pfl/pfl-dynamic/4.0.1/pfl-dynamic-4.0.1.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/pfl/pfl-basic/4.0.1/pfl-basic-4.0.1.jar /jars/
ADD http://central.maven.org/maven2/org/eclipse/persistence/org.eclipse.persistence.core/2.7.4/org.eclipse.persistence.core-2.7.4.jar /jars/
ADD http://central.maven.org/maven2/org/apache/ws/xmlschema/xmlschema-core/2.2.2/xmlschema-core-2.2.2.jar /jars/
ADD http://central.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar /jars/
ADD http://central.maven.org/maven2/org/glassfish/pfl/pfl-asm/4.0.1/pfl-asm-4.0.1.jar /jars/
ADD http://central.maven.org/maven2/org/eclipse/persistence/org.eclipse.persistence.asm/2.7.4/org.eclipse.persistence.asm-2.7.4.jar /jars/
ADD http://central.maven.org/maven2/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar /jars/
ADD http://central.maven.org/maven2/org/apache/neethi/neethi/3.0.3/neethi-3.0.3.jar /jars/
ADD http://central.maven.org/maven2/org/apache/tomcat/tomcat-annotations-api/9.0.17/tomcat-annotations-api-9.0.17.jar /jars/
ADD http://repo.spring.io/plugins-release/io/springfox/springfox-spring-web/2.9.0/springfox-spring-web-2.9.0.jar /jars/
ADD http://repo.spring.io/plugins-release/io/springfox/springfox-schema/2.9.0/springfox-schema-2.9.0.jar /jars/
ADD http://repo.spring.io/plugins-release/io/springfox/springfox-swagger-common/2.9.0/springfox-swagger-common-2.9.0.jar /jars/
ADD http://central.maven.org/maven2/io/micrometer/micrometer-core/1.1.4/micrometer-core-1.1.4.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/spring-oxm/5.1.6.RELEASE/spring-oxm-5.1.6.RELEASE.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/ws/spring-ws-core/3.0.7.RELEASE/spring-ws-core-3.0.7.RELEASE.jar /jars/
ADD http://mirrors.ibiblio.org/pub/mirrors/maven2/stax/stax-api/1.0.1/stax-api-1.0.1.jar /jars/
ADD http://central.maven.org/maven2/org/springframework/boot/spring-boot-autoconfigure/2.1.4.RELEASE/spring-boot-autoconfigure-2.1.4.RELEASE.jar /jars/
